entities:
  playlist:
    table: Playlist
    key: PlaylistId
    displayName: Playlist
    displayNameI18n:
      en-US: Playlist
      zh-CN: 播放列表
      ja-JP: プレイリスト
    softDelete: false
    isPublic: true
    paging: { pageSize: 10, mode: numbered }
    layout:
      forms: { columns: 1, order: [Name] }
      filters: { columns: 1 }
    columns:
      PlaylistId: { type: int, identity: true, label: ID, labelI18n: { en-US: ID, zh-CN: 编号, ja-JP: ID }, searchable: false, sortable: true }
      Name: { type: string, label: Name, labelI18n: { en-US: Name, zh-CN: 名称, ja-JP: 名前 }, searchable: true, sortable: true }
    forms:
      Name: { type: string, label: Name, labelI18n: { en-US: Name, zh-CN: 名称, ja-JP: 名前 }, editable: true }
    filters: {}
